### ISSUE TITLE
Installing from PyPI seems to not work

### ISSUE THREAD

**Issue by kaimast** [matplotlib/mplcairo#25]
Installing using pip and git does work fine however... See the output below. 

```
kai@kai-thinkpad ~/u/thesis-kai-mast (master) [1]> pip3 install mplcairo
Collecting mplcairo
  Using cached mplcairo-0.2.tar.gz (113 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ievy3i1q/mplcairo/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ievy3i1q/mplcairo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ievy3i1q/mplcairo/pip-egg-info
         cwd: /tmp/pip-install-ievy3i1q/mplcairo/
    Complete output (23 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ievy3i1q/mplcairo/setup.py", line 241, in <module>
        setup(
      File "/tmp/pip-install-ievy3i1q/mplcairo/setupext.py", line 55, in __new__
        setuptools.setup(**kwargs)
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 718, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 781, in resolve
        dist = best[req.key] = env.best_match(
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1078, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/usr/lib/python3/dist-packages/setuptools/installer.py", line 83, in fetch_build_egg
        raise DistutilsError('the `allow-hosts` option is not supported '
    distutils.errors.DistutilsError: the `allow-hosts` option is not supported when using pip to install requirements.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

kai@kai-thinkpad ~/u/thesis-kai-mast (master) [1]> pip3 install git+https://github.com/matplotlib/mplcairo
Collecting git+https://github.com/matplotlib/mplcairo
  Cloning https://github.com/matplotlib/mplcairo to /tmp/pip-req-build-sq8psipm
  Running command git clone -q https://github.com/matplotlib/mplcairo /tmp/pip-req-build-sq8psipm
Requirement already satisfied: matplotlib>=2.2 in /usr/lib/python3/dist-packages (from mplcairo==0.2.post47+gdb53d25) (3.1.2)
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from mplcairo==0.2.post47+gdb53d25) (7.0.0)
Requirement already satisfied: pycairo>=1.16.0 in /usr/lib/python3/dist-packages (from mplcairo==0.2.post47+gdb53d25) (1.16.2)
Building wheels for collected packages: mplcairo
  Building wheel for mplcairo (setup.py) ... done
  Created wheel for mplcairo: filename=mplcairo-0.2.post47+gdb53d25-cp38-cp38-linux_x86_64.whl size=3721364 sha256=14f5c6b1c9172e897753f9c88210e5b653085637197e7a7426b92c70fd131451
  Stored in directory: /tmp/pip-ephem-wheel-cache-18hnup9o/wheels/7a/bc/b0/e2e879bde6d9d500436db343e9164de25f77ae7b2ca94d4998
Successfully built mplcairo
Installing collected packages: mplcairo
Successfully installed mplcairo-0.2.post47+gdb53d25
```

**Comment by anntzer** [comment]
Yes, I know the problem.  I need to make a new release (basically setuptools changed since the last release), but this is blocked because OSX CI has been failing for a while (see discussion starting at https://github.com/matplotlib/mplcairo/pull/24#issuecomment-610036173) and I can't fix it locally.

**Comment by anntzer** [comment]
0.3 has been released on PyPI.  Please give it a try.

**Comment by kaimast** [comment]
Seems to be fixed. Thanks!
